# Generated by Django 5.0.3 on 2024-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invoice_id',
            field=models.IntegerField(blank=True, default=1708, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order_id',
            field=models.IntegerField(blank=True, default=4560, null=True),
        ),
    ]
