# Generated by Django 5.0.3 on 2024-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
