# Generated by Django 5.0.3 on 2024-04-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_ticket_total_cost2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_cost2',
        ),
    ]
